fix:  "modify the width of the mobile user avatar"
yinxin630/fiora pull request #229
Opened 2020-09-03 14:55 UTC by AlvinMi

2020-09-10 00:41 UTC, yinxin630 requested changes

2020-09-10 00:41 UTC, yinxin630 commented on build/webpack.base.conf.ts
> +                        loader: 'ts-loader',
There should sync with master branch

2020-09-10 00:41 UTC, yinxin630 commented on package.json
> +    "start": "cross-env NODE_ENV=production ts-node --transpile-only server/main.ts",
There should sync with master branch

2020-09-10 00:41 UTC, yinxin630 commented on client/modules/Sidebar/SelfInfo.tsx
> +                                    // viewMode={1}
comments should be delete

2020-09-10 00:41 UTC, yinxin630 commented on client/modules/Sidebar/SelfInfo.tsx
> +                                    style={{ height: 400, width: '100%' }}
height should equal to width. We can use JavaScript to calculate it if no other good ways

refer <https://www.w3ctech.com/topic/1483>

2020-09-12 14:03 UTC, yinxin630 commented
`webpack.base.conf.js` 和 `package.json` 我曾经回退过, 你现在的分支上是不对的, 改到和 master 一致

2020-09-12 14:05 UTC, yinxin630 commented
`Unit Test` check 失败的问题和你没关系

2020-09-13 16:24 UTC, AlvinMi commented
我怎么才能和你的 master 分支一致。我现在的分支修改了，还是没有更新 `webpack.base.conf.js` 和 `package.json` 回退的内容。

我使用下面的命令同步更新：

```bash
git checkout master
git fetch upstream -ap
git rebase upstream/master
```

会提示有冲突。

```bash

首先，回退分支以便在上面重放您的工作...
应用：Revert "pull from fiora"
使用索引来重建一个（三方合并的）基础目录树...
M       Dockerfile
M       README.md
A       client/App.jsx
A       client/components/components.less
A       client/modules/main/chatPanel/chat/Chat.less
A       client/modules/main/chatPanel/chat/Message.jsx
A       client/modules/main/sidebar/AppDownload.jsx
A       client/modules/main/sidebar/SelfInfo.jsx
M       doc/INSTALL.ZH.md
M       doc/INSTALL.md
M       doc/README.ZH.md
A       server/routes/system.js
A       utils/sound.js
A       utils/voice.js
回落到基础版本上打补丁及进行三方合并...
冲突（修改/删除）：utils/voice.js 在 HEAD 中被删除，在 Revert "pull from fiora" 中被 修改。utils/voice.js 的 Revert "pull from fiora" 版本被保留。
自动合并 utils/playSound.ts
冲突（修改/删除）：server/routes/system.js 在 HEAD 中被删除，在 Revert "pull from fiora" 中被 修改。server/routes/system.js 的 Revert "pull from fiora" 版本被保留。
删除 docker-compose.yaml
自动合并 doc/README.ZH.md
冲突（内容）：合并冲突于 doc/README.ZH.md
自动合并 doc/INSTALL.md
冲突（内容）：合并冲突于 doc/INSTALL.md
自动合并 doc/INSTALL.ZH.md
冲突（内容）：合并冲突于 doc/INSTALL.ZH.md
冲突（修改/删除）：client/modules/main/sidebar/SelfInfo.jsx 在 HEAD 中被删除，在 Revert "pull from fiora" 中被 修改。client/modules/main/sidebar/SelfInfo.jsx 的 Revert "pull from fiora" 版本被保留。
冲突（修改/删除）：client/modules/main/sidebar/AppDownload.jsx 在 HEAD 中被删除，在 Revert "pull from fiora" 中被 修改。client/modules/main/sidebar/AppDownload.jsx 的 Revert "pull from fiora" 版本被保留。
冲突（修改/删除）：client/modules/main/chatPanel/chat/Message.jsx 在 HEAD 中被删除，在 Revert "pull from fiora" 中被 修改。client/modules/main/chatPanel/chat/Message.jsx 的 Revert "pull from fiora" 版本被保留。
冲突（修改/删除）：client/modules/main/chatPanel/chat/Chat.less 在 HEAD 中被删除，在 Revert "pull from fiora" 中被 修改。client/modules/main/chatPanel/chat/Chat.less 的 Revert "pull from fiora" 版本被保留。
冲突（修改/删除）：client/components/components.less 在 HEAD 中被删除，在 Revert "pull from fiora" 中被 修改。client/components/components.less 的 Revert "pull from fiora" 版本被保留。
冲突（修改/删除）：client/App.jsx 在 HEAD 中被删除，在 Revert "pull from fiora" 中被 修改。client/App.jsx 的 Revert "pull from fiora" 版本被保留。
自动合并 README.md
冲突（内容）：合并冲突于 README.md
冲突（修改/删除）：Dockerfile 在 Revert "pull from fiora" 中被删除，在 HEAD 中被 修改。Dockerfile 的 HEAD 版本被保留。
error: 无法合并变更。
打补丁失败于 0001 Revert "pull from fiora"
用 'git am --show-current-patch' 命令查看失败的补丁

手工解决所有冲突，执行 "git add/rm <冲突的文件>" 标记
冲突已解决，然后执行 "git rebase --continue"。您也可以执行
"git rebase --skip" 命令跳过这个提交。如果想要终止执行并回到
"git rebase" 执行之前的状态，执行 "git rebase --abort"。
```

2020-09-14 01:03 UTC, yinxin630 commented
一般我是直接在当前分支执行 `git pull --rebase origin master` 来同步的, 有冲突就解决冲突, 然后 `git add . && git rebase --continue` 就 ok 了
你目前的 commit 历史太乱了, 建议重新从 master 拉个分支, 然后 `git cherry-pick [commit id]` 把有效的那次 commit 拉过来就行

2020-09-15 13:46 UTC, closed without merging